language: node_js
before_script:
  - npm install -g gulp-cli
script: gulp
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: gh-pages
  on:
    branch: master